Добавить DeviceLocationRepository #4
MAVIKE/yad-android pull request #12
Opened 2021-03-25 19:36 UTC by ilyalevushkin

resolve #4.
Добавлен класс DeviceLocationRepository, позволяющий получать геолокацию устройства в виде широты и долготы.
Используется [Build location-aware apps](https://developer.android.com/training/location/).
При создании класса необходимо передать ему в качестве параметра Activity, вызывающей его.

У класса 3 публичных метода:
- getLocation() - получает геолокацию и возвращает liveData<Location>.
- startUpdateLocation(timeUpdateLocation) - начинает обновлять liveData<Location> каждые timeUpdateLocation секунд.
- stopUpdateLocation() - прекращает обновление геолокации.

В классе присутствует проверка прав доступа пользователя, а также проверка, включена ли геолокация. В случае не выполнения проверки, методы ничего не делают (программа не завершается аварийно).

В классе нет вызова запроса пользователя на разрешение прав доступа приложению, а также просьбы включить геолокацию в настройках, поскольку эта часть относится к ui.

2021-03-27 17:30 UTC, vovac12 requested changes

2021-03-27 17:30 UTC, vovac12 commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +    // возвращает true, если геолокация перестала обновляться
Что тут имеется ввиду? Кто возвращает true?

2021-03-27 17:30 UTC, vovac12 commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +        // проверка, есть ли права доступа у activity
Не лучше сделать что-то вроде этого?
```java
int permission = ActivityCompat.checkSelfPermission(this, ACCESS_FINE_LOCATION);
if (permission != PERMISSION_GRANTED) {
  ActivityCompat.requestPermissions(this,
    new String[]{ACCESS_FINE_LOCATION},
    LOCATION_PERMISSION_REQUEST);
}
```
В последних версиях андроида права запрашиваются по необходимости.

2021-03-27 17:30 UTC, vovac12 commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +    public void startUpdateLocation(int timeUpdateLocation) {
Скорее всего класс `DeviceLocationRepo` будет использоваться следующим образом.
```
DeviceLocationRepo repo = new DeviceLocationRepo(activity);
repo.startUpdateLocation(1);
```
И в таком случае нельзя сказать как отработает вторая функция, потому что `isLocationRecievedOnce` может измениться в любой момент.
В общем, эта функция ведёт себя очень неопределенно (для вызывающей стороны) )

2021-03-27 17:47 UTC, ilyalevushkin commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +        // проверка, есть ли права доступа у activity
Да, я тоже хотел вначале так сделать, но столкнулся со следующей проблемой:
В таком случае, необходимо в классе прописать логику реакции приложения на отклонение запроса прав доступа пользователем и на их принятие. Для этого, в классе Activity, вызывающей DeviceLocationRepository, необходимо переопределить метод onRequestPermissionsResult(). Разве можно это сделать внутри класса DeviceLocationRepository?
Пример кода onRequestPermissionsResult ниже:
`@Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String permissions[],
                                           @NonNull int[] grantResults) {
        if (requestCode == PERMISSION_REQUEST_CODE) {
            if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                putLocationInTextViews();
            }
        } else {
            super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        }
    }`

2021-03-27 17:57 UTC, ilyalevushkin commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +    public void startUpdateLocation(int timeUpdateLocation) {
isLocationReceivedOnce изменяется на true единожды, при первом успешном вызове getLocation(). Не очень понимаю, о какой неопределенности идет речь.

Про то что класс будет использоваться следующим образом.

```java
DeviceLocationRepo repo = new DeviceLocationRepo(activity);
repo.startUpdateLocation(1);
```

В таком случае можно написать как-то так:
```java
DeviceLocationRepo repo = new DeviceLocationRepo(activity);
LiveData<Location> loc = repo.getLocation();
repo.startUpdateLocation(1);
```
Google требует вначале хотя бы один раз получить геолокацию, а потом начинать обновлять ее.
![image](https://user-images.githubusercontent.com/36894819/112729782-fa004c80-8f3e-11eb-962b-6f9236676a7e.png)

2021-03-27 17:57 UTC, ilyalevushkin commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +    // возвращает true, если геолокация перестала обновляться
пардон, ошибочка, ничего она не возвращает

2021-03-27 18:05 UTC, ilyalevushkin commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +        // проверка, есть ли права доступа у activity
Да и вообще, довольно странно это. Отдавать yad_core возможность что-то делать в ui. Я думал, у нас yad_core используется для вычислительных штук всяких и к интерфейсу отношения не должен иметь.

2021-03-27 18:07 UTC, RyazMax commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +    public void startUpdateLocation(int timeUpdateLocation) {
```java
DeviceLocationRepo repo = new DeviceLocationRepo(activity);
LiveData<Location> loc = repo.getLocation();
repo.startUpdateLocation(1);
```
может все таки спрятать от пользователя необходимость знать, что нужно запустить getLocation? А сделать это самим, при необходимости, в методе startUpdateLocation. Тогда пользователь сможет пользоваться репозиторием в удобном виде.

Неопределенность заключается в том, что isLocationReceivedOnce проставляется внутри каллбека, следовательно присутствует асинхронный характер выполнения задачи. Т.е нельзя ожидать, сразу же после вызова метода getLocation флаг будет проставлен (он проставится в другом потоке).

2021-03-27 18:09 UTC, RyazMax commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +        // проверка, есть ли права доступа у activity
Обязательно ли это делать в репозитории? Т.е можем ли мы добавить запрос прав в репозитории, а уже ответственность за обработку возложить на пользователя репозитория: чтобы он сам реализовал этот метод при использовании репозитория?

2021-03-27 18:10 UTC, RyazMax commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +    // возвращает true, если геолокация перестала обновляться
Исправлено в https://github.com/MAVIKE/yad-android/pull/12/commits/03e72a367544faed9137fc25a817fde4983993b6

2021-03-27 19:08 UTC, ilyalevushkin commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +    public void startUpdateLocation(int timeUpdateLocation) {
Понял, да. Изменил. Теперь startUpdateLocation() не требует вызова getLocation. Внутри себя он сам запрашивает последнюю актуальную геолокацию и в случае успеха, запускает цикл обновления геолокации. Также, был удален флаг isLocationReceivedOnce за ненадобностью. Также, теперь startUpdateLocation() возвращает LiveData<Location>.

2021-03-27 19:13 UTC, RyazMax requested changes

2021-03-27 19:13 UTC, RyazMax commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +interface Expression {
В Java принято выделять сущности в отдельные файлы, так что давай вынесем его в отдельный файл. И может быть лучше использовать название ```Command```?

2021-03-27 19:13 UTC, RyazMax commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +            data.postValue(loc);
Мы используем postValue потому что это не ui поток?

2021-03-27 19:13 UTC, RyazMax commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +        public void onLocationResult(@NotNull LocationResult locationResult) {
В requestLocation есть проверка location на не null, здесь она точно не нужна?

2021-03-27 19:19 UTC, vovac12 commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +interface Expression {
И метод `execute()`. Заодно посмотри, нет ли чего-то стандартного для этого?

2021-03-27 19:19 UTC, ilyalevushkin commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +            data.postValue(loc);
Да, этим руководствовался

2021-03-27 19:23 UTC, RyazMax commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +interface Expression {
А еще лучше использовать стандартный интерфейс https://docs.oracle.com/javase/8/docs/api/java/lang/Runnable.html

2021-03-27 19:26 UTC, ilyalevushkin commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +        public void onLocationResult(@NotNull LocationResult locationResult) {
так она же есть тут. @NotNull стоит перед LocationResult. Если locationResult будет null, то и метод не вызовется, не?
Если ты про саму location после этого действия:
android.location.Location location = locationResult.getLastLocation();
то если тут проверять location на null, android studio подсвечивает, что condition is always true. Поэтому и не стал проверять.

2021-03-27 19:28 UTC, ilyalevushkin commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +        // проверка, есть ли права доступа у activity
Мне показалось, что это будет неудобно и странно, что вызываем в одном месте, а обрабатываем совсем в другом. Но ладно, сделаю так значит.

2021-03-27 19:29 UTC, RyazMax commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +        public void onLocationResult(@NotNull LocationResult locationResult) {
Ок

2021-03-28 08:41 UTC, ilyalevushkin commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +interface Expression {
Исправлено в https://github.com/MAVIKE/yad-android/pull/12/commits/56c8aa84650f6d5abbc6d8f28d03e0d96d279e8e

2021-03-28 09:32 UTC, RyazMax commented on yad_core/src/main/java/ru/m2d/yad_core/services/device/repos/DeviceLocationRepo.java
> +        // проверка, есть ли права доступа у activity
Посовещались, решили, что удобнее будет сделать логику запроса прав в коде использующем репозиторий, так как обработка результата происходит в callback'е следовательно и продолжение работы должно происходить там же

2021-03-28 09:33 UTC, RyazMax approved these changes

2021-03-28 09:59 UTC, vovac12 approved these changes

2021-03-28 12:54 UTC, merged